/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as loanContractSol from "./loanContract.sol";
export type { loanContractSol };
export type { MockERC20 } from "./MockERC20";
