/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as loanContractSol from "./loanContract.sol";
export { MockERC20__factory } from "./MockERC20__factory";
